version: '3'
services:
  db:
    image: "postgres:13"
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - pgdata:/var/lib/postgresql/data

  sonarqube:
    image: "sonarqube:9.5.0-community"
    ports:
        - "9000:9000"
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
    depends_on:
      - db
    volumes:
      - ./sonarqube:/opt/sonarqube/conf
  
volumes:
  pgdata: